---
fullname: Selinger
shortname: Selinger
organization: thery
community: false
dune: false
action: true

synopsis: Formalisation of Selinger's paper

description: |-

  Formalisation of Selinger's paper :
  Remarks on Matsumoto and Amano’s normal form
 
authors:
- name: Laurent Théry

maintainers:
- name: Laurent Théry
  nickname: thery

opam-file-maintainer: thery@sophia.inria.fr

license:
  fullname: MIT License
  identifier: MIT

supported_rocq_versions:
  text: '9.1 or later'
  opam: '{(>= "9.1")}'

dependencies:
- opam:
    name: rocq-mathcomp-ssreflect
    version: '{(>= "2.5.0")}'
  description: |-
    [MathComp ssreflect 2.5.0 or later](https://math-comp.github.io)
- opam:
    name: rocq-mathcomp-algebra
    version: '{(>= "2.5.0")}'
  description: |-
    [MathComp algebra 2.5.0 or later](https://math-comp.github.io)

- opam:
    name: rocq-mathcomp-field
    version: '{(>= "2.5.0")}'
  description: |-
    [MathComp field 2.5.0 or later](https://math-comp.github.io)

tested_rocq_opam_versions:
- version: '2.5.0-rocq-prover-9.1'
  repo: 'mathcomp/mathcomp'

namespace: Selinger

keywords:
- name: sum of two squares
- name: fermat theorem


---