---
fullname: Selinger
shortname: Selinger
organization: thery
community: false
dune: false
action: true

synopsis: Formalisation of Selinger's paper

description: |-

  Formalisation of Selinger's paper :
  Remarks on Matsumoto and Amano’s normal form
 
authors:
- name: Laurent Théry

maintainers:
- name: Laurent Théry
  nickname: thery

opam-file-maintainer: thery@sophia.inria.fr

license:
  fullname: MIT License
  identifier: MIT

supported_coq_versions:
  text: '8.17 or later'
  opam: '{(>= "8.17")}'

dependencies:
- opam:
    name: coq-mathcomp-ssreflect
    version: '{(>= "1.17.0")}'
  description: |-
    [MathComp ssreflect 1.17 or later](https://math-comp.github.io)
- opam:
    name: coq-mathcomp-algebra
    version: '{(>= "1.17.0")}'
  description: |-
    [MathComp algebra 1.17 or later](https://math-comp.github.io)

- opam:
    name: coq-mathcomp-field
    version: '{(>= "1.17.0")}'
  description: |-
    [MathComp field 1.17 or later](https://math-comp.github.io)

tested_coq_opam_versions:
- version: '1.17.0-coq-8.17'
  repo: 'mathcomp/mathcomp'

namespace: Selinger

keywords:
- name: sum of two squares
- name: fermat theorem


---